# Site settings
title: Maryum Mateen
email: maryummateen19@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "maryummateen.com" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
